FROM node:alpine

# Set working directory
WORKDIR /mood

# Set environment to production
ENV NODE_ENV production

# Copies project requirements into working directory
COPY package*.json ./

# Copies requirements.txt into working directory
COPY ./requirements.txt /mood/requirements.txt

# install python and pip
RUN apk add --no-cache python3 py3-pip

# Install requirements
RUN pip install --no-cache-dir --upgrade -r /mood/requirements.txt

# Install dependencies
RUN npm ci

# Command instructions
CMD ["npm", "run", "dev"]
