FROM node:alpine

# Set working directory
WORKDIR /mood

# Copies project requirements into working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Command instructions
CMD ["npm", "run", "dev"]
